spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123123   # 这里换成你自己的
    driver-class-name: com.mysql.cj.jdbc.Driver
